[package]
authors = ["Manuel Sopena Ballesteros <msopena@cscs.ch>"]
name = "silla"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
reqwest = { version = "0.12.5", default-features = false, features = ["blocking", "json", "rustls-tls", "socks"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
anyhow = "1.0.44"
config = { version = "0.13.2", features = [ "toml" ] } 			# used to read manta configuration file
toml_edit = "0.20.2"							# used to edit manta configuration file
log = "0.4.17"
log4rs = "1.2.0" 							# Docs about pattern encoder https://docs.rs/log4rs/0.10.0/log4rs/encode/pattern/index.html
dialoguer = "0.11.0"
directories = "4.0.1"							# XDG Base Directory Specification
comfy-table = "6.1.1"							# used to print mata's command output to stdout as tables
clap = { version = "4.5.7", features = ["derive"] }
rustls = "0.23.11"
rustls-pemfile = "2.1.2"
base64 = "0.22.1"
thiserror = "1.0.56"
dirs = "5.0.1"
