# This file is used by docker compose to set environment variables
# For more information about how it is read and how to override items in it, see the docs:
#   https://docs.docker.com/compose/environment-variables/set-environment-variables/

# Set the system name and domain which are used for certs
SYSTEM_NAME="foobar"
SYSTEM_DOMAIN="openchami.cluster"

POSTGRES_USER="ochami"

# Set DB passwords
POSTGRES_PASSWORD="KQmglz4rbda9jNJ3fvogaBzs6YYQ9r8C"
BSS_POSTGRES_PASSWORD="8jxyKKGXD9lQmd17rd1rG7YSjn3MexRf"
SMD_POSTGRES_PASSWORD="PAwIFHCvxkIe5edFCt6dy3NZ3e6c4d8N"
HYDRA_POSTGRES_PASSWORD="hSpzZzrFLNn2hDMKdorcpwsPYrqZmMFz"
HYDRA_SYSTEM_SECRET="p1t7E5o42pABt38pBBgbrFQZKiPIGBzc"
LOCAL_IP="10.6.128.230"
DNSMASQ_ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsImtpZCI6IjBjMmI5ZjBjLThjYTctNGI4MS04MWQyLTllODdjZTI5MDEzYSIsInR5cCI6IkpXVCJ9.eyJhdWQiOltdLCJjbGllbnRfaWQiOiJjM2M5ZTcwNy1lZjA5LTRmYjEtYmYzMS0wZWY4ODU0YmYwN2UiLCJleHAiOjE3MzAyMDg0OTYsImV4dCI6e30sImlhdCI6MTczMDIwNDg5NiwiaXNzIjoiaHR0cHM6Ly9mb29iYXIub3BlbmNoYW1pLmNsdXN0ZXIvIiwianRpIjoiMWMwMDZkMGUtYjBmNy00M2Q3LWJlNDMtN2NmN2E4ZTEwN2QzIiwibmJmIjoxNzMwMjA0ODk2LCJzY3AiOlsib3BlbmlkIiwic21kLnJlYWQiXSwic3ViIjoiYzNjOWU3MDctZWYwOS00ZmIxLWJmMzEtMGVmODg1NGJmMDdlIn0.o2UfDN4p056XHqlj3q0gaAAQlsaCnfGi2cT2hADSrioYP5qtEz9chabVTJz0_7qj7VzeC1QvGd1wSvMGc9zejZ-Zn2S-J-fz_h-yZkdlQ7zQWrzCIaRTeWJXzBvJqZAMUZ8_cfkNE12-eMzzvzc3uWJGxSHbPGJdQaSoWMr9eZ2c9iR0uInGVaIpXo0uBXuJ1Ed3l_f_ZgQLHxLDkiSGfRfM2OeE-uAR9VfkF99XfS1qt9p9LU6f06WHehMe7didJIhJFaz1j-pyHfSxT8s7h3b2GYMGrV0R5YIacv8LfSWooET-l05cOVRwVwNCFdNp7u8h95uivdAGU2v5sAy8zpR4idocyza6hj34g5J51dQzisT16C1MWEJ_PGW0CrOJ02f0ASgAfv8mfU1F7Ha5EJuyIkF2JkJXWyP-2kODQQD39_Jh9D-odWjGziJMcbnHecjArfRmRTeioIASSh4gGL_FJCe6oCfOjbNjnucUrUEJElChyHeVBpfeQcOxK651f7aFBWsFATHQnBZ-iQ3cD0jpd81oO-QIOSI5lHaggg6iZ7J7LJcpqeRbR3GImi-t9AWXIhWMtGc100EUvh3FSR-I8gebkqPyRzQ3wV0JJnEnnDW_FXJNjGCkAV4_edkPaqEntJcT49yVsEt7IQpZBpeY323IUrAxuoO_n8Bvd-E"
