#name: Shared jobs workflow
#
#on:
#  workflow_call:
#
#jobs:
#  changed_files:
#    runs-on: ubuntu-latest
#    name: Detect changed files
#    outputs:
#      manta_any_changed: ${{ steps.changed-files-yaml.outputs.manta_any_changed }}
#      manta_all_changed_files: ${{ steps.changed-files-yaml.outputs.manta_all_changed_files }}
#      manta_backend_dispatcher_any_changed: ${{ steps.changed-files-yaml.outputs.manta_backend_dispatcher_any_changed }}
#      manta_backend_dispatcher_all_changed_files: ${{ steps.changed-files-yaml.outputs.manta_backend_dispatcher_all_changed_files }}
#      manta_ws_any_changed: ${{ steps.changed-files-yaml.outputs.manta_ws_any_changed }}
#      manta_ws_all_changed_files: ${{ steps.changed-files-yaml.outputs.manta_ws_all_changed_files }}
#      ochami_rs_any_changed: ${{ steps.changed-files-yaml.outputs.ochami_rs_any_changed }}
#      ochami_rs_all_changed_files: ${{ steps.changed-files-yaml.outputs.ochami_rs_all_changed_files }}
#      csm_rs_any_changed: ${{ steps.changed-files-yaml.outputs.csm_rs_any_changed }}
#      csm_rs_all_changed_files: ${{ steps.changed-files-yaml.outputs.csm_rs_all_changed_files }}
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#          fetch-depth: 0  # Required for changed-files to compare commits
#
#      - name: Get changed files
#        id: changed-files-yaml
#        uses: tj-actions/changed-files@v46
#        with:
#          files_yaml: |
#            manta:
#              - crates/manta/**
#            manta_backend_dispatcher:
#              - crates/manta-backend-dispatcher/**
#            manta_ws:
#              - crates/manta-ws/**
#            ochami_rs:
#              - crates/ochami-rs/**
#            csm_rs:
#              - crates/csm-rs/**
#
#  build_crates:
#      needs: changed_files
#      if: contains(github.event.head_commit.message, 'Release ')
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          include:
#            - name: manta
#              path: crates/manta
#              output_prefix: manta
#              os: ubuntu-latest
#            - name: manta-backend-dispatcher
#              path: crates/manta-backend-dispatcher
#              output_prefix: manta_backend_dispatcher
#              os: ubuntu-latest
#            - name: manta-ws
#              path: crates/manta-ws
#              output_prefix: manta_ws
#              os: ubuntu-latest
#            - name: ochami-rs
#              path: crates/ochami-rs
#              output_prefix: ochami_rs
#              os: ubuntu-latest
#            - name: csm-rs
#              path: crates/csm-rs
#              output_prefix: csm_rs
#              os: ubuntu-latest
#            - name: manta
#              path: crates/manta
#              output_prefix: manta
#              os: macos-latest
#              target: x86_64-apple-darwin
#            - name: manta
#              path: crates/manta
#              output_prefix: manta
#              os: macos-latest
#              target: aarch64-apple-darwin
#      steps:
#        - uses: actions/checkout@v4
#          with:
#            submodules: recursive
#
#        - name: Install Rust
#          uses: dtolnay/rust-toolchain@stable
#          with:
#            toolchain: stable
#
#        - name: Build
#          if: ${{ needs.changed_files.outputs[format('{0}_any_changed', matrix.output_prefix)] == 'true' }}
#          run: |
#            cargo --version
#            rustc --version
#            if [[ -n "${{ matrix.target }}" ]]; then
#              rustup target add ${{ matrix.target }}
#            fi
#            cd ${{ matrix.path }}
#            if [[ -n "${{ matrix.target }}" ]]; then
#              cargo build --release --target ${{ matrix.target }}
#            else
#              cargo build --release
#            fi
#
#        - name: Upload artifacts
#          if: ${{ needs.changed_files.outputs[format('{0}_any_changed', matrix.output_prefix)] == 'true' }}
#          uses: actions/upload-artifact@v4
#          with:
#            name: ${{ matrix.name }}-${{ runner.os }}${{ matrix.target && format('-{0}', matrix.target) || '' }}-binary
#            path: ${{ matrix.path }}/target/${{ matrix.target && format('{0}/', matrix.target) || '' }}release/${{ matrix.name }}
