name: Test and Build Crates

on:
  push:
    branches:
      - '**'  # Run on all branches
    paths:
      - 'crates/**'  # Trigger on changes in crates directory
      - 'Cargo.toml'  # Trigger on workspace Cargo.toml changes
      - 'Cargo.lock'  # Trigger on lockfile changes
  pull_request:
    branches:
      - '**'
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

permissions:
  contents: read  # Required for checking out code
  pull-requests: write  # Optional, for commenting on PRs if needed

env:
  CARGO_TERM_COLOR: always  # Enable colored output for Cargo

jobs:
  detect-changed-crates:
    runs-on: ubuntu-latest
    outputs:
      crates: ${{ steps.set-crates.outputs.crates }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate diff

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            crates/**
            Cargo.toml
            Cargo.lock

      - name: Determine changed crates
        id: set-crates
        run: |
          CHANGED_CRATES=()
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            # List all crates
            ALL_CRATES=("csm-rs" "manta" "manta-backend-dispatcher" "manta-ws" "ochami-rs")
            for crate in "${ALL_CRATES[@]}"; do
              # Check if any file in the crate's directory or workspace files changed
              if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q -e "^crates/$crate/" -e "^Cargo.toml" -e "^Cargo.lock"; then
                CHANGED_CRATES+=("$crate")
              fi
            done
          fi
          # Convert array to JSON for matrix
          if [ ${#CHANGED_CRATES[@]} -eq 0 ]; then
            echo "crates=[]" >> $GITHUB_OUTPUT
          else
            CRATES_JSON=$(printf '%s\n' "${CHANGED_CRATES[@]}" | jq -R . | jq -s .)
            echo "crates=$CRATES_JSON" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-and-build:
    runs-on: ubuntu-latest
    needs: detect-changed-crates
    if: needs.detect-changed-crates.outputs.crates != '[]'  # Only run if crates changed
    strategy:
      matrix:
        crate: ${{ fromJson(needs.detect-changed-crates.outputs.crates) }}
      fail-fast: false  # Continue testing other crates if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests for ${{ matrix.crate }}
        run: |
          cargo test --package ${{ matrix.crate }} --all-features
        working-directory: .

      - name: Build crate ${{ matrix.crate }}
        run: |
          cargo build --package ${{ matrix.crate }} --release
        working-directory: .
